# Environment based on https://github.com/rmcgibbo/python-appveyor-conda-example
environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python27_32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_NPY: "18"

    - PYTHON: "C:\\Python27_64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"
      CONDA_NPY: "18"

    - PYTHON: "C:\\Python33_32"
      PYTHON_VERSION: "3.3"
      PYTHON_ARCH: "32"
      CONDA_PY: "33"
      CONDA_NPY: "18"

    - PYTHON: "C:\\Python33_64"
      PYTHON_VERSION: "3.3"
      PYTHON_ARCH: "64"
      CONDA_PY: "33"
      CONDA_NPY: "18"

    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      CONDA_PY: "34"
      CONDA_NPY: "18"

    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      CONDA_PY: "34"
      CONDA_NPY: "18"

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as numpy and llvmpy
  - powershell .\\continuous-integration\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: false

test_script:
  - python setup.py build_ext --inplace
  - python setup.py install
  - python runtests.py
