package:
  name: numba-hsa
  version: 0.21.0

source:
  path: ../..

build:
  number: 0
  entry_points:
    - pycc = numba.pycc:main
    - numba = numba.numba_entry:main

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - python
    - argparse        [py26]
    - numpy x.x
    # On channel https://binstar.org/numba/
    - llvmlite 0.8*
    - funcsigs       [py26 or py27]
    - singledispatch [py26 or py27 or py33]
  run:
    - python
    - argparse        [py26]
    - numpy x.x
    # On channel https://binstar.org/numba/
    - llvmlite 0.8*
    - funcsigs       [py26 or py27]
    - singledispatch [py26 or py27 or py33]
    - libhlc
test:
  requires:
    - argparse       [py26]
    - unittest2      [py26]
    - jinja2
  files:
    - mandel.py
  commands:
    - pycc -h
    - numba -h
